<?php
/**
 * @file
 * Hook implementations for the Clientside Validation jQuery module.
 */

/**
 * Implements hook_js_alter().
 */
function clientside_validation_jquery_js_alter(&$javascript, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {
  if (\Drupal::moduleHandler()->moduleExists('ckeditor')) {
    $library_discovery = \Drupal::service('library.discovery');
    $ckeditor = $library_discovery->getLibraryByName('ckeditor', 'drupal.ckeditor');
    foreach ($ckeditor['js'] as $ckeditor_file) {
      if (strpos($ckeditor_file['data'], 'ckeditor.js') !== FALSE) {
        break;
      }
    }
    $cv_jquery = $library_discovery->getLibraryByName('clientside_validation_jquery', 'cv.jquery.validate');
    foreach ($cv_jquery['js'] as $cv_jquery_file) {
      if (strpos($cv_jquery_file['data'], 'cv.jquery.validate.js') !== FALSE) {
        break;
      }
    }
    // Add our scripts after ckeditor.
    if (isset($javascript[$ckeditor_file['data']]) && isset($javascript[$cv_jquery_file['data']])) {
      $javascript[$cv_jquery_file['data']]['weight'] = $javascript[$ckeditor_file['data']]['weight'] + 0.001;
    }
  }
}

/**
 * Implements hook_clientside_validation_validator_info_alter().
 */
function clientside_validation_jquery_clientside_validation_validator_info_alter(&$validators) {
  foreach ($validators as &$validator) {
    $validator['attachments']['library'][] = 'clientside_validation_jquery/cv.jquery.validate';
  }
}

/**
 * Implements hook_library_info_alter().
 */
function clientside_validation_jquery_library_info_alter(&$libraries, $extension) {
  if ($extension == 'clientside_validation_jquery' && isset($libraries['jquery.validate'])) {
    if (!file_exists(drupal_get_path('module', 'clientside_validation_jquery') . '/js/lib/dist/jquery.validate.js')) {
      // Previously we told users to extract the /dist folder. Make sure we still
      // support this.
      if (file_exists(drupal_get_path('module', 'clientside_validation_jquery') . '/js/lib/jquery.validate.js')) {
        unset($libraries['jquery.validate']['js']['js/lib/dist/jquery.validate.js']);
        $libraries['jquery.validate']['js']['js/lib/jquery.validate.js'] = [];
        unset($libraries['jquery.validate.additional']['js']['js/lib/dist/additional-methods.js']);
        $libraries['jquery.validate']['js']['js/lib/additional-methods.js'] = [];
      }
      else {
        // Use CDN version if local version doesn't exist.
        unset($libraries['jquery.validate']['js']['js/lib/dist/jquery.validate.js']);
        $libraries['jquery.validate']['js']['https://cdn.jsdelivr.net/jquery.validation/1.14.0/jquery.validate.min.js'] = ['type' => 'external'];
        unset($libraries['jquery.validate.additional']['js']['js/lib/dist/additional-methods.js']);
        $libraries['jquery.validate.additional']['js']['http://cdn.jsdelivr.net/jquery.validation/1.14.0/additional-methods.min.js'] = ['type' => 'external'];
      }
    }
  }
}
