<?php
/**
 * @file
 * Hook implementations for the Clientside Validation jQuery module.
 */

/**
 * Implements hook_clientside_validation_validator_info_alter().
 */
function clientside_validation_jquery_clientside_validation_validator_info_alter(&$validators) {
  foreach ($validators as &$validator) {
    $validator['attached']['library'][] = 'clientside_validation_jquery/jquery.validate';
  }
}
